# Generated by Django 2.2.6 on 2019-10-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publihed_date',
            new_name='published_date',
        ),
    ]
